//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPortal.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BIPortalEntities : DbContext
    {
        public BIPortalEntities()
            : base("name=BIPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<UserRoleMapping> UserRoleMappings { get; set; }
        public virtual DbSet<PermissionMaster> PermissionMasters { get; set; }
        public virtual DbSet<RoleRightsMapping> RoleRightsMappings { get; set; }
        public virtual DbSet<WorkspaceReportsMaster> WorkspaceReportsMasters { get; set; }
        public virtual DbSet<UserAccessRight> UserAccessRights { get; set; }
        public virtual DbSet<WorkFlowMaster> WorkFlowMasters { get; set; }
        public virtual DbSet<WorkSpaceOwnerMaster> WorkSpaceOwnerMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
    
        public virtual ObjectResult<GetWorkspaceOwner_Result> GetWorkspaceOwner()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWorkspaceOwner_Result>("GetWorkspaceOwner");
        }
    
        public virtual ObjectResult<GetWorkspaceOwner1_Result> GetWorkspaceOwner1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWorkspaceOwner1_Result>("GetWorkspaceOwner1");
        }
    }
}
